services:
  redis:
    image: redis:7.4.3
    container_name: sv_redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/db/redis/data:/data
    networks:
      - my-network

  minio:
    image: minio/minio
    container_name: sv_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./backend/db/minIO/data:/data
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    container_name: sv_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    networks:
      - my-network

  event_loader:
    build:
      context: ./backend
      dockerfile: Dockerfile.event_loader
    container_name: sv_event_loader
    volumes:
      - ./backend:/app
    networks:
      - my-network
    restart: unless-stopped

  streamlit:
    build:
      context: ./backend
      dockerfile: Dockerfile.streamlit 
    command: streamlit run streamlit/main.py
    container_name: sv_streamlit
    volumes:
      - ./backend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - my-network

  frontend:
    build: ./frontend
    container_name: sv_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    external: true